USERNAME=$(echo -n 'admin' | base64)
PASSPHRASE=$(echo -n 'admin' | base64)
NAMESPACE=istio-system
kubectl create namespace $NAMESPACE
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Secret
metadata:
  name: kiali
  namespace: $NAMESPACE
  labels:
    app: kiali
type: Opaque
data:
  username: $USERNAME
  passphrase: $PASSPHRASE
EOF
---
kind: Service
apiVersion: v1
metadata:
  name: kiali-test
  namespace: istio-system
  labels:
    app: kiali
spec:
  selector:
    app: kiali
  type: NodePort
  ports:
    - name: http-kiali
      protocol: TCP
      port: 20001
      nodePort: 32143